
INSTALLED_APPS = [   
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'import_export',
    'rest_framework',
    'django_filters',
    'admin_object_actions',
    'django_object_actions',
    'admin_totals',
    "admincharts",
    'apps.finance',
    'apps.dashboard',
]
