
import os

# SECURE_HSTS_SECONDS = os.environ.get('SECURE_HSTS_SECONDS', 15)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
# SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', False)
# SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', False)
# CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', False)
# SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', False)