# Generated by Django 3.2.4 on 2021-07-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Nro')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('fin_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.financialinstrument')),
            ],
        ),
    ]
