# Generated by Django 3.2.4 on 2021-07-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20210702_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
