# Generated by Django 3.2.4 on 2021-07-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210702_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('url', models.CharField(max_length=1000, verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='financialinstrument',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.typeinstrument'),
        ),
    ]
