# Generated by Django 3.2.4 on 2021-07-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20210703_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinstrument',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL'),
        ),
    ]
