# Generated by Django 3.2.4 on 2021-07-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_typeinstrument_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('ytd', models.FloatField()),
                ('monthly_varation', models.FloatField()),
            ],
        ),
    ]
