# Generated by Django 3.2.4 on 2021-07-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_ipc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipc',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
